### ISSUE TITLE
NX run

### ISSUE THREAD

**Issue by baranero** [ErfanSeidipoor/bright-resume#86]
I'm having trouble starting. After following the step-by-step installation instructions, I encounter a problem.

![1](https://github.com/ErfanSeidipoor/bright-resume/assets/94863094/7e1af6ef-e8dd-4380-9dba-f67b437ade0a)

After restarting command I got the message that I was missing module @nrwl/nx-win32-x64-msvc.

![2](https://github.com/ErfanSeidipoor/bright-resume/assets/94863094/8cacbf3c-49ee-45fe-93af-9d872ef5c1f9)

After installing the package it sends a message that a project with that name could not be found

![3](https://github.com/ErfanSeidipoor/bright-resume/assets/94863094/52120612-c13e-442c-8061-84fdfef44b5f)

**Comment by ErfanSeidipoor** [comment]
This is a monorepo project that has been implemented using [Nx](https://nx.dev/) as its platform. To run one of our applications, you'll need to use specific project names. Currently, we have two main projects: `app` and `web`.

To serve the `app` project, you can use the following command:
`nx serve app`

For the 'web' project, use the command:
`nx serve web`

Our primary focus lies in the development of UI components, which we showcase using Storybook. To view these components, you can execute the following command:
`nx storybook components`

Feel free to reach out if you have any more questions or need further assistance.

We're actively working on enhancing the documentation to provide clearer instructions. Please stay tuned for updates.

**Comment by baranero** [comment]
After typing in bash `nx serve app` : 

`NX Cannot find project 'app'`

For `web` works fine. Also typing `nx storybook components ` returns

![1](https://github.com/ErfanSeidipoor/bright-resume/assets/94863094/dd8a37af-6e21-4ddb-b151-3cfd85c0c3ee)

**Comment by AliShirzad** [comment]
It is better to use the VSCode extension to run the Nx application. From there, you have access to serve, run test,s and more commands with each application.

Name: Nx Console
Id: nrwl.angular-console
Description: The UI for Nx & Lerna
Version: 18.8.0
Publisher: nrwl
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=nrwl.angular-console
